---
title: "thought experiment"
format: pdf
editor: visual
---

# Definitions

A true effect is the relationship between two or more valid constructs. The interaction of these constructs is what causes the effect. We have constructs A and B which make true effect C, We also have constructs X and Y which causes effect Z. How do i know which true effect the observed effects k belong to?

Could their be such a thing as construct heterogeneity and methodological heterogeneity? that might be a simple way of expressing it. If we have heterogeneity coming from the fact that the higher order constructs in the studies are different vs heterogeneity coming from the fact that the methods are different. So the constructs providing the observed effect are the same, but the method makes the effect incomparable. Perhaps design heterogeneity would be better, say we only have one construct that we are interested in, eg intelligence, and the effect we are interested in is improved intelligence from training. If we have different measures for intelligence and different training interventions we will have variation in the effects since our model is imprecise.

Maybe what i don't like about clinical heterogeneity is that they lump intervention and individuals together. I do not think they are a comparable source of heterogeneity. Individuals have some type of randomness associated with them but intervention is very systematic and design based.


# review guidelines 
Additionally, is worth mentioning that multiple other guidelines for conducting reviews exists to help address issues of heterogeneity beyond what is detailed above. A few examples are the realist review guidelines(RAMESES), Campbell review guidelines, preferred reporting items for systematic reviews and meta-analyses(PRISMA, Joanna Briggs Institute(JBI) handbook among many others that are specialized to a particular field. However the concept of substantive heterogeneity is not always directly addressed. Furthermore it is not always apparent how the concept of substantive heterogeneity should be handled even when guidelines exists. This illustrates the push and pull between the specificity of a research question and its contribution to general/theoretical knowledge. When the substantive heterogeneity is too high, the resulting synthesis will be too diffuse, but if it is too narrow, the resulting synthesis will not be interesting to anyone. This is commonly referred to as the conflict between ‘’lumpers’’ and ‘’splitters’’(REF). This goes to show that even when an underlying structure of conducting a review is present, individual authors will have to make judgements on the comparability of studies on a case-by-case basis, meaning that an in-depth understanding of the potential sources of substantive heterogeneity is needed. 
