---
title: "validity and hetrogeneity"
format: pdf
editor: visual
bibliography: references.bib
---

One of the reasons behind why isolating true effects in psychology or any social science is hard is because defining and knowing what our measurements are measuring is impossible. Any non-physical unit of measurement will have this issue. This problem is what inspires areas of research interested in *validity*. What constitutes validity is a philosophical questions that targets our subjective beliefs about epistemology and ontology [@macklin2022]. For the purpose of this paper, validity refers to the reliability and accuracy of an inference. There exists many frameworks for categorising validity, since we are mainly interested in the validity in terms of inferences we will utilize the Campbellian framework [@shadish2002] [@macklin2022]. Briefly put, this framework posits that there exists four types of validity which influences the quality of our inferences. These are external, internal, construct, and statistical validity. External validity is the extent to which inferences holds to and across different settings, participants, persons and outcomes(find lucas paper and refer). Internal validity, or more accurately put, local molar causal validity, refers to whether an experiment capture a causal relationship between outcome and treatment. Cook, Campbell and Shadish says: \`\`internal validity is about whether a complex and inevitably multivariate treatment package caused a difference in some variable-as-it-was-measured within the particular setting, time frames, and kinds of units that were sampled in a study." Construct validity refers to the congruence between the variable-as-it-was-measured and the psychological concept/construct we are interested in. Statistical validity refers to whether the statistical conclusions drawn from the analysis accurately represents the observed data.

Together these validity types create a theoretical way of assessing the quality of the inferences we can draw from a paper. External validity targeting the generalisability of units, construct validity targeting the generalisability of the measures, and internal validity assessing whether causal relationships can be established. To fully understand how heterogeneity is caused, we need to evaluate not only the validity of individual studies but the validity of the synthesis and the inferences we draw from our review.
